### ISSUE TITLE
2D attn_mask shape error during stage 3 training

### ISSUE THREAD

**Issue by NohSeongRae** [sherwinbahmani/tc4d#8]
Thank you for the interesting work. I'm trying to reproduce the results. Stage1 and 2 worked fine, but stage 3 failed due to subsequent errors. I think there's something I missed since there's no related issue in this repo. 
PyTorch version: 2.3.0+cu121
CUDA version: 12.1

.sh file (I seperated .sh file of stage 1,2, and 3):

pwd
which python
hostname

seed=0
gpu=0
exp_root_dir=/data/rhosunr99/github/tc4d

scene_setup_path=configs_prompts/a_deer_walking.yaml

ckpt=/data/rhosunr99/github/tc4d/tc4d_stage_2/a_deer_walking@20240717-145030/ckpts/last.ckpt
python launch.py --config configs/tc4d_stage_3_40_gb.yaml --train --gpu $gpu exp_root_dir=$exp_root_dir seed=$seed syst>

exit 0

Logs:
/data/rhosunr99/github/tc4d
/data/rhosunr99/anaconda3/envs/threestudio/bin/python
ariel-k1
/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[rank: 0] Seed set to 0
[INFO] Loading VideoCrafter ...
[INFO] Loaded Video Crafter!
[INFO] Using prompt [a deer walking] and negative prompt [low motion, static statue, not moving, no motion]
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
Loading model from cache file: /home/rhosunr99/.cache/huggingface/hub/models--VideoCrafter--VideoCrafter2/snapshots/7b4079838622fcba3fc2c9575210df3ed1cb8d69/model.ckpt
>>> model checkpoint loaded.
/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/rhosunr99/github/tc4d/threestudio/models/prompt_processors/videocrafter_prompt_processor.py", line 91, in spawn_func
    text_embeddings = model.cond_stage_model.encode(prompts)
  File "/data/rhosunr99/github/tc4d/threestudio/models/guidance/videocrafter/lvdm/modules/encoders/condition.py", line 235, in encode
    return self(text)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/rhosunr99/github/tc4d/threestudio/models/guidance/videocrafter/lvdm/modules/encoders/condition.py", line 212, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "/data/rhosunr99/github/tc4d/threestudio/models/guidance/videocrafter/lvdm/modules/encoders/condition.py", line 219, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "/data/rhosunr99/github/tc4d/threestudio/models/guidance/videocrafter/lvdm/modules/encoders/condition.py", line 231, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/open_clip/transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/open_clip/transformer.py", line 250, in attention
    return self.attn(
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1266, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/data/rhosunr99/anaconda3/envs/threestudio/lib/python3.10/site-packages/torch/nn/functional.py", line 5382, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (10, 10).
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
Loading model from cache file: /home/rhosunr99/.cache/huggingface/hub/models--VideoCrafter--VideoCrafter2/snapshots/7b4079838622fcba3fc2c9575210df3ed1cb8d69/model.ckpt
>>> model checkpoint loaded.
Traceback (most recent call last):
  File "/data/rhosunr99/github/tc4d/launch.py", line 180, in <module>
    main()
  File "/data/rhosunr99/github/tc4d/launch.py", line 109, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/data/rhosunr99/github/tc4d/threestudio/systems/base.py", line 40, in __init__
    self.configure()
  File "/data/rhosunr99/github/tc4d/threestudio/systems/tc4d.py", line 92, in configure
    self.prompt_processor_video = threestudio.find(self.cfg.prompt_processor_type_video)(
  File "/data/rhosunr99/github/tc4d/threestudio/utils/base.py", line 63, in __init__
    self.configure(*args, **kwargs)
  File "/data/rhosunr99/github/tc4d/threestudio/models/prompt_processors/base.py", line 191, in configure
    self.load_text_embeddings()
  File "/data/rhosunr99/github/tc4d/threestudio/models/prompt_processors/base.py", line 249, in load_text_embeddings
    self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]
  File "/data/rhosunr99/github/tc4d/threestudio/models/prompt_processors/base.py", line 267, in load_from_cache
    raise FileNotFoundError(
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/6122e74e7eee4afd2af8107cd1d9f389.pt for model VideoCrafter/VideoCrafter2 and prompt [a deer walking] not found.

I'm looking forward to your reply.

**Comment by sherwinbahmani** [comment]
Hi,

This is weird. Have you tried deleting .threestudio_cache?
It seems like some issue with the text embedding having size mismatches. Is the conda environment done cleanly, so not from an existing one but from an empty environment?

**Comment by NohSeongRae** [comment]
Thank you for advice. I will try both ways and report the results.

**Comment by sherwinbahmani** [comment]
Please reopen if this issue is not solved.

**Comment by sherwinbahmani** [comment]
I just realized this issue can be fixed with: pip install open-clip-torch==2.24.0
